### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by Aneeqasif** [kovidgoyal/iv#1]
```
 python3 ~/Downloads/git_down/iv/ ~/Pictures/walls/dt-walls         
Compiling RapydScript...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aneeq/Downloads/git_down/iv/__main__.py", line 7, in <module>
    main()
  File "/home/aneeq/Downloads/git_down/iv/iv/main.py", line 171, in main
    setup_profile(files)
  File "/home/aneeq/Downloads/git_down/iv/iv/view.py", line 105, in setup_profile
    insert_scripts(ans, files_data(files), client_script())
  File "/home/aneeq/Downloads/git_down/iv/iv/view.py", line 49, in client_script
    if subprocess.Popen(['rapydscript', 'compile', '-C', build_cache, '--js-version', '6', entry, '-o', compiled]).wait() != 0:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'rapydscript'

```

**Comment by kovidgoyal** [comment]
You need to install rapydscript-ng
